"""
Django settings for ecuapass project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_URL = '/staticfiles/'
STATIC_ROOT = os.path.join (BASE_DIR, 'staticfiles')
#STATICFILES_DIRS = (os.path.join(BASE_DIR,'appdocs/static'),)

# Static file serving.
# https://whitenoise.readthedocs.io/en/stable/django.html#add-compression-and-caching-support
STORAGES = {
	# ...
	"staticfiles": {
		"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
	},
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-*e!pw-wwqm=az^o+oy0a$2u$rhkf(05i&!c3ic8@49dsh9&hmi')

# Added djang CORS policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
CSRF_TRUSTED_ORIGINS = ["https://*.railway.app","https://127.0.0.1", "https://192.168.1.91"]  # To fix CSRF django validation

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['web-production-d3df.up.railway.app', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://web-production-d3df.up.railway.app']

# Application definition

INSTALLED_APPS = [
	'appdocs.apps.AppdocsConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecuapass.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates'),],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'ecuapass.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Remote railway database
DATABASES = {
	'default': {
		'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
		'NAME'	  : os.environ.get ('PGDATABASE'),
		'USER'	  : os.environ.get ('PGUSER'),
		'PASSWORD': os.environ.get ('PGPASSWORD'),
		'HOST'	  : os.environ.get ('PGHOST'),
		'PORT'	  : os.environ.get ('PGPORT'),
	}
}

# Local postgress database
#DATABASES = {
#	 'default': {
#		 'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
#		 'NAME': 'ecuapassdocsdb',
#		 'USER': 'lg',
#		 'PASSWORD': 'lge',
#		 'HOST': 'localhost',
#		 'PORT': '5432',
#	 }
#}

# Default sqlite: For testing
#DATABASES = {
#	 'default': {
#		 'ENGINE': 'django.db.backends.sqlite3',
#		 'NAME': BASE_DIR / 'db.sqlite3',
#	 }
#}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{ 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
	{ 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
	{ 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
	{ 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Set the language code to Spanish for Colombia
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Update database configuration from $DATABASE_URL environment variable (if defined)
import dj_database_url

if 'DATABASE_URL' in os.environ:
	DATABASES['default'] = dj_database_url.config(
		conn_max_age=500,
		conn_health_checks=True,
	)

