"""
Django settings for ecuapass_web project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, os.path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL       = '/staticfiles/'
STATIC_ROOT      = os.path.join (BASE_DIR, 'staticfiles')  # Example path
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'creador/static')]

# Disable Django's built-in static file handling in favor of Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cczhgbp2b=v=4lpq*728wssns(1v0bf$9c5v)f*%b6e3cfhi^o'

# Added djang CORS policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
CSRF_TRUSTED_ORIGINS = ["https://*.railway.app","https://127.0.0.1", "https://192.168.1.91"]  # To fix CSRF django validation


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'ecudocs.apps.EcudocsConfig',
	'shared.apps.SharedConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecuapass_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecuapass_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Remote railway database
#DATABASES = {
#    'default': {
#        'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
#        'NAME'    : os.environ.get ('PGDATABASE'),
#        'USER'    : os.environ.get ('PGUSER'),
#        'PASSWORD': os.environ.get ('PGPASSWORD'),
#        'HOST'    : os.environ.get ('PGHOST'),
#        'PORT'    : os.environ.get ('PGPORT'),
#    }
#}

# Local postgress database
#DATABASES = {
#    'default': {
#        'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'ecuapassdocsdb',
#        'USER': 'lg',
#        'PASSWORD': 'lge',
#        'HOST': 'localhost',
#        'PORT': '5432',
#    }
#}

# sqlite: For testing
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Set the language code to Spanish for Colombia
LANGUAGE_CODE = 'es-co'
#LANGUAGE_CODE = 'en-us'

# Set the timezone to the appropriate one for Colombia
TIME_ZONE = 'America/Bogota'
#TIME_ZONE = 'UTC'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

