# Generated by Django 5.0.1 on 2024-01-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='cartaporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shared.cartaporte'),
        ),
    ]
