# Generated by Django 5.0.1 on 2024-01-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_cartaporte_manifiestos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaporte',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='cartaporte',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='cartaporte',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='manifiesto',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Cartaporte',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='Manifiesto',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
